name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.x
          6.0.x

    - name: Build projects
      working-directory: src
      run: dotnet build -c Release

    - name: Pack package 1
      working-directory: src/Iwate.Commander
      run: dotnet pack -c Release -p:Version=${{github.event.release.tag_name}} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
    
    - name: Pack package 2
      working-directory: src/Iwate.AzureFunctions.Middlewares.Commander
      run: dotnet pack -c Release -p:Version=${{github.event.release.tag_name}} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: Publish package to NuGet.org 1
      working-directory: src/Iwate.Commander/bin/Release/
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }}
    
    - name: Publish package to NuGet.org 2
      working-directory: src/Iwate.AzureFunctions.Middlewares.Commander/bin/Release/
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }}